/**
 * Scroll To
 * Copyright (c) 2007-2012 Ariel Flesler - aflesler(at)gmail(dot)com | http://flesler.blogspot.com
 * Dual licensed under MIT and GPL.
 * @author Ariel Flesler
 * @version 1.4.3
 */
;(function($){var h=$.scrollTo=function(a,b,c){$(window).scrollTo(a,b,c)};h.defaults={axis:'xy',duration:parseFloat($.fn.jquery)>=1.3?0:1,limit:true};h.window=function(a){return $(window)._scrollable()};$.fn._scrollable=function(){return this.map(function(){var a=this,isWin=!a.nodeName||$.inArray(a.nodeName.toLowerCase(),['iframe','#document','html','body'])!=-1;if(!isWin)return a;var b=(a.contentWindow||a).document||a.ownerDocument||a;return/webkit/i.test(navigator.userAgent)||b.compatMode=='BackCompat'?b.body:b.documentElement})};$.fn.scrollTo=function(e,f,g){if(typeof f=='object'){g=f;f=0}if(typeof g=='function')g={onAfter:g};if(e=='max')e=9e9;g=$.extend({},h.defaults,g);f=f||g.duration;g.queue=g.queue&&g.axis.length>1;if(g.queue)f/=2;g.offset=both(g.offset);g.over=both(g.over);return this._scrollable().each(function(){if(!e)return;var d=this,$elem=$(d),targ=e,toff,attr={},win=$elem.is('html,body');switch(typeof targ){case'number':case'string':if(/^([+-]=)?\d+(\.\d+)?(px|%)?$/.test(targ)){targ=both(targ);break}targ=$(targ,this);if(!targ.length)return;case'object':if(targ.is||targ.style)toff=(targ=$(targ)).offset()}$.each(g.axis.split(''),function(i,a){var b=a=='x'?'Left':'Top',pos=b.toLowerCase(),key='scroll'+b,old=d[key],max=h.max(d,a);if(toff){attr[key]=toff[pos]+(win?0:old-$elem.offset()[pos]);if(g.margin){attr[key]-=parseInt(targ.css('margin'+b))||0;attr[key]-=parseInt(targ.css('border'+b+'Width'))||0}attr[key]+=g.offset[pos]||0;if(g.over[pos])attr[key]+=targ[a=='x'?'width':'height']()*g.over[pos]}else{var c=targ[pos];attr[key]=c.slice&&c.slice(-1)=='%'?parseFloat(c)/100*max:c}if(g.limit&&/^\d+$/.test(attr[key]))attr[key]=attr[key]<=0?0:Math.min(attr[key],max);if(!i&&g.queue){if(old!=attr[key])animate(g.onAfterFirst);delete attr[key]}});animate(g.onAfter);function animate(a){$elem.animate(attr,f,g.easing,a&&function(){a.call(this,e,g)})}}).end()};h.max=function(a,b){var c=b=='x'?'Width':'Height',scroll='scroll'+c;if(!$(a).is('html,body'))return a[scroll]-$(a)[c.toLowerCase()]();var d='client'+c,html=a.ownerDocument.documentElement,body=a.ownerDocument.body;return Math.max(html[scroll],body[scroll])-Math.min(html[d],body[d])};function both(a){return typeof a=='object'?a:{top:a,left:a}}})(jQuery);

/**
 scrollup v2.2.0
 Author: Mark Goodyear - http://markgoodyear.com
 Git: https://github.com/markgoodyear/scrollup
 Copyright 2014 Mark Goodyear.
 Licensed under the MIT license
 http://www.opensource.org/licenses/mit-license.php
 Twitter: @markgdyr
 */
(function(c,b,a){c.fn.scrollUp=function(d){if(!c.data(a.body,"scrollUp")){c.data(a.body,"scrollUp",true);c.fn.scrollUp.init(d)}};c.fn.scrollUp.init=function(d){var g=c.fn.scrollUp.settings=c.extend({},c.fn.scrollUp.defaults,d),e=(g.scrollTitle)?g.scrollTitle:g.scrollText,f;if(g.scrollTrigger){f=c(g.scrollTrigger)}else{f=c("<a/>",{id:g.scrollName,href:"#top",title:e})}f.appendTo("body");if(!(g.scrollImg||g.scrollTrigger)){f.html(g.scrollText)}f.css({display:"none",position:"fixed",zIndex:g.zIndex});if(g.activeOverlay){c("<div/>",{id:g.scrollName+"-active"}).css({position:"absolute",top:g.scrollDistance+"px",width:"100%",borderTop:"1px dotted"+g.activeOverlay,zIndex:g.zIndex}).appendTo("body")}scrollEvent=c(b).scroll(function(){if(g.scrollFrom==="top"){scrollDis=g.scrollDistance}else{scrollDis=c(a).height()-c(b).height()-g.scrollDistance}switch(g.animation){case"fade":c((c(b).scrollTop()>scrollDis)?f.fadeIn(g.animationInSpeed):f.fadeOut(g.animationOutSpeed));break;case"slide":c((c(b).scrollTop()>scrollDis)?f.slideDown(g.animationInSpeed):f.slideUp(g.animationOutSpeed));break;default:c((c(b).scrollTop()>scrollDis)?f.show(0):f.hide(0))}});f.click(function(h){h.preventDefault();c("html, body").animate({scrollTop:0},g.scrollSpeed,g.easingType)})};c.fn.scrollUp.defaults={scrollName:"scrollUp",scrollDistance:300,scrollFrom:"top",scrollSpeed:300,easingType:"linear",animation:"fade",animationInSpeed:200,animationOutSpeed:200,scrollTrigger:false,scrollText:"Scroll to top",scrollTitle:false,scrollImg:false,activeOverlay:false,zIndex:2147483647};c.fn.scrollUp.destroy=function(d){c.removeData(a.body,"scrollUp");c("#"+c.fn.scrollUp.settings.scrollName).remove();c("#"+c.fn.scrollUp.settings.scrollName+"-active").remove();if(c.fn.jquery.split(".")[1]>=7){c(b).off("scroll",d)}else{c(b).unbind("scroll",d)}};c.scrollUp=c.fn.scrollUp})(jQuery,window,document);
